# Generated by Django 5.0.7 on 2024-08-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('documentary', 'Documentary'), ('drama', 'Drama'), ('romance', 'Romance')], max_length=20, null=True),
        ),
    ]
