# Generated by Django 5.0.7 on 2024-08-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_urls',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
