services:
  web:
    image: videoflix_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
