# Generated by Django 5.0.7 on 2024-10-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
